In [1]:
import pandas as pd

Answer the following questions:

* Calculate the birth rate and death rate for each state. For the purposes of this question you can define the rate as the # of births/deaths divided by the total population.  
* Create a new column appended to the first dataset with the net population change (births-deaths) by state.  
* Using the column from (2), project out the future population by state in 5 years, assuming the population change remains the same (on an absolute/n-count basis). You can assume each state's net transfer in/out rate from folks moving is 0 for this question's sake.
 * For example, if CA's population is 30M and the birth-death rate is 150k, then the projected population in 5 years is just 30,000,000 + 150,000*5 = 30.75M.

In [2]:
births_deaths = pd.read_csv("https://raw.githubusercontent.com/erood/interviewqs.com_code_snippets/master/Datasets/us_state_births.csv")

In [3]:
pop_by_state = pd.read_csv("https://raw.githubusercontent.com/erood/interviewqs.com_code_snippets/master/Datasets/us_state_populations.csv")

In [8]:
merged = births_deaths.merge(pop_by_state, on='State')

In [9]:
merged['birth_rate'] = merged['Births'] / merged['Population']
merged['death_rate'] = merged['Deaths'] / merged['Population']

In [11]:
merged['population_change'] = merged['Births'] - merged['Deaths']

In [13]:
merged['5_year_pop_prediction'] = merged['Population'] + (merged['population_change'] * 5)

In [15]:
merged.sort_values('State')

,State,Births,Deaths,Population,birth_rate,death_rate,population_change,5_year_pop_prediction
0,Alabama,58941,53238,4887871,0.012059,0.010892,5703,4916386
1,Alaska,10445,4411,737438,0.014164,0.005982,6034,767608
2,Arizona,81872,57758,7171646,0.011416,0.008054,24114,7292216
3,Arkansas,37520,32588,3013825,0.012449,0.010813,4932,3038485
4,California,471658,268189,39865590,0.011831,0.006727,203469,40882935
5,Colorado,64382,38063,5695564,0.011304,0.006683,26319,5827159
6,Connecticut,35221,31312,3572665,0.009858,0.008764,3909,3592210
7,Delaware,10855,9178,967171,0.011223,0.009490,1677,975556
8,Florida,223630,203636,21299325,0.010499,0.009561,19994,21399295
9,Georgia,129243,83098,10519475,0.012286,0.007899,46145,10750200
10,Hawaii,17517,11390,1420491,0.012332,0.008018,6127,1451126
11,Idaho,22181,14011,1754208,0.012644,0.007987,8170,1795058
12,Illinois,149390,109721,12741080,0.011725,0.008612,39669,12939425
13,Indiana,82170,65597,6691878,0.012279,0.009802,16573,6774743
14,Iowa,38430,30530,3156145,0.012176,0.009673,7900,3195645
15,Kansas,36519,27063,2911505,0.012543,0.009295,9456,2958785
16,Kentucky,54752,48212,4468402,0.012253,0.010790,6540,4501102
17,Louisiana,61018,45804,4659978,0.013094,0.009829,15214,4736048
18,Maine,12298,14676,1338404,0.009189,0.010965,-2378,1326514
19,Maryland,71641,49926,6042718,0.011856,0.008262,21715,6151293
20,Massachusetts,70702,58803,6902149,0.010243,0.008520,11899,6961644
21,Michigan,111426,97602,9995915,0.011147,0.009764,13824,10065035
22,Minnesota,68595,44371,5611179,0.012225,0.007908,24224,5732299
23,Mississippi,37357,32280,2986530,0.012508,0.010809,5077,3011915
24,Missouri,73034,31876,6126452,0.011921,0.005203,41158,6332242
25,Montana,11799,10200,1062305,0.011107,0.009602,1599,1070300
26,Nebraska,25821,16878,1929268,0.013384,0.008748,8943,1973983
27,Nevada,35756,24657,3034392,0.011784,0.008126,11099,3089887
28,New Hampshire,12116,12504,1356458,0.008932,0.009218,-388,1354518
29,New Jersey,101250,74846,8908520,0.011366,0.008402,26404,9040540
30,New Mexico,23767,18673,2095428,0.011342,0.008911,5094,2120898
31,New York,229737,155358,19542209,0.011756,0.007950,74379,19914104
32,North Carolina,120125,93157,10383620,0.011569,0.008972,26968,10518460
33,North Dakota,10737,6415,760077,0.014126,0.008440,4322,781687
34,Ohio,136832,123648,11689442,0.011706,0.010578,13184,11755362
35,Oklahoma,50214,40452,3943079,0.012735,0.010259,9762,3991889
36,Oregon,43631,36624,4190713,0.010411,0.008739,7007,4225748
37,Pennsylvania,137745,135656,12807060,0.010755,0.010592,2089,12817505
38,Rhode Island,10638,10157,1057315,0.010061,0.009606,481,1059720
39,South Carolina,57029,49441,5084127,0.011217,0.009725,7588,5122067
40,South Dakota,12134,7996,882235,0.013754,0.009063,4138,902925
41,Tennessee,81016,70096,6770010,0.011967,0.010354,10920,6824610
42,Texas,382050,198106,29206997,0.013081,0.006783,183944,30126717
43,Utah,48585,18035,3161105,0.015370,0.005705,30550,3313855
44,Vermont,5655,6007,626299,0.009029,0.009591,-352,624539
45,Virginia,100391,68579,8517685,0.011786,0.008051,31812,8676745
46,Washington,87562,56995,7535591,0.011620,0.007563,30567,7688426
47,West Virginia,18675,23276,1805832,0.010341,0.012889,-4601,1782827
48,Wisconsin,64975,52681,5813568,0.011176,0.009062,12294,5875038
49,Wyoming,6903,4768,577737,0.011948,0.008253,2135,588412